### ISSUE TITLE
rspec style?

### ISSUE THREAD

**Issue by wli3** [JayBazuzi/Okra#1]
More cool this way... and more important, reduce the duplication of test name and the test itself. Usually test framework can generate the full test name.

``` ruby
describe HelloWorld do 
   context “When testing the HelloWorld class” do 
      
      it "The say_hello method should return 'Hello World'" do 
         hw = HelloWorld.new 
         message = hw.say_hello 
         expect(message).to eq "Hello World!" 
      end
      
   end 
end
```

mochajs in JavaScript
```javascript
var assert = require('assert');
describe('Array', function() {
  describe('#indexOf()', function() {
    it('should return -1 when the value is not present', function() {
      assert.equal(-1, [1,2,3].indexOf(4));
    });
  });
});
```

**Comment by JayBazuzi** [comment]
I like the way that BBD-oriented frameworks let you write the name in English instead of an in-language identifier.

What if each describe was a file or directory? So in `vector\find.cpp` you'd write:

```
Example("returns -1 when the value is not present", []
{
    Assert(vector<int>{1, 2, 3}.find(4) == -1);
}
```

And the test output can look like:

```
    [PASS] vector find returns -1 when the value is not present
```

What do you think?

**Comment by wli3** [comment]
I do know the benefit of using directory. But I am more concerned about legacy code base since the existing folder structure will be like. 

_main/private/service/src/service/abstract/deprecated/will/core_

And there are more legacy code base in C++.

But the way, Elixir takes tests as document to another level. http://elixir-lang.org/getting-started/mix-otp/docs-tests-and-with.html

**Comment by JayBazuzi** [comment]
@wli3 I think what you're talking about is covered by [Igloo](https://github.com/joakimkarlsson/igloo). Do you agree?

**Comment by JayBazuzi** [comment]
I'm going to let this go unless a brilliant insight or a serious problem brings it back.
