### ISSUE TITLE
Name this project

### ISSUE THREAD

**Issue by JayBazuzi** [JayBazuzi/Okra#2]
The name Okra doesn't carry any meaning. At best, it's a loose reference to Cucumber. (My grandmother grew cukes and okra).

Should we pick a meaningful name? Should it have the word "test" or "spec" in it? Should it be a clever acronym?

To get a sense of what other names are in the same, I did a quick Google search:

- igloo
- Catch
- GTest
- Microsoft Unit Testing Framework
- CPP UNIT

If you have an idea for a name, put it in a comment.

**Comment by JayBazuzi** [comment]
Okra

**Comment by JayBazuzi** [comment]
OkraTest

**Comment by JayBazuzi** [comment]
OkraSpec

**Comment by JayBazuzi** [comment]
Jay's Awesome C++ TDD/BDD/ATDD/microtest/test-as-spec framework

I like this one because it has my name in it.

**Comment by wli3** [comment]
Well... the last name is _honest and complete_

One downside of "non-serious" framework naming is you really don't know what it does when you read the package file. For example: cancancan, factory_girl. But on the contrary, things like J2EE has no fun at all.

So I prefer the middle ground OkraSpec

((what about JTAF -- **J**ay's Awesome C++ TDD/BDD/ATDD/microtest/**t**est-**a**s-spec **f**ramework pronounce Jay-tough))

**Comment by JayBazuzi** [comment]
Sticking with Okra until a better name overwhelms me.
