### ISSUE TITLE
When running the binary directly, the first character of the text name is missing (FreeBSD 11, gcc6)

### ISSUE THREAD

**Issue by smeredith** [JayBazuzi/Okra#24]
When running via ctest, the tests pass and the output looks good:

    $ ctest
    Test project /usr/home/smeredith/src/Okra/build
        Start 1: format_path_for_display
    1/4 Test #1: format_path_for_display ..........   Passed    0.01 sec
        Start 2: get_common_root_of_file_paths
    2/4 Test #2: get_common_root_of_file_paths ....   Passed    0.01 sec
        Start 3: works_with_using_namespace
    3/4 Test #3: works_with_using_namespace .......   Passed    0.01 sec
        Start 4: works_without_using_namespace
    4/4 Test #4: works_without_using_namespace ....   Passed    0.01 sec

But when I just run the binary, the name of the test in the output is missing the first char. For example:

    $ ./format_path_for_display 
    "ormat path for display" - the name of the test is based on the path

**Comment by smeredith** [comment]
In Okra.h, line 51, you have an off-by-1 error. The +1 should not be there.

Your current tests assume Windows filename separators. I don't know how those are supposed to behave when run on a Unix file system.

**Comment by smeredith** [comment]
On Unix:

    path(R"(C:\foo\bar.cpp)").remove_filename()

returns "" because it can't find a "/" path separator.

**Comment by JayBazuzi** [comment]
This code has been removed.
