### ISSUE TITLE
On Unix, tests with Windows filesystem paths fail

### ISSUE THREAD

**Issue by smeredith** [JayBazuzi/Okra#26]
$ ./get_common_root_of_file_paths 
    "/get common root of file paths" - common root of two related paths
    "/get common root of file paths" - same path just returns directoryresult == R"(C:\foo\)" - assert FAILED - "" != C:\foo\

    "/get common root of file paths" - common root of vector of pathsresult == R"(C:\foo\)" - assert FAILED - "" != C:\foo\

This is because 

    path(R"(C:\foo\bar.cpp)").remove_filename()

returns "" because it can't find a "/" path separator.
Perhaps the tests should just use the "/" separator?
What happens if we run on Windows like that?

**Comment by JayBazuzi** [comment]
This now works on Unix.
