### ISSUE TITLE
Remove 'using' from header

### ISSUE THREAD

**Issue by bobbymcr** [JayBazuzi/Okra#5]
Header files should not have 'using' statements. References:
http://stackoverflow.com/a/5849668
http://www.gotw.ca/publications/c++cs.htm (item 59)

**Comment by JayBazuzi** [comment]
From my naive point of view, I would think that `using namespace std;` in a PCH would be a reasonable exception to this rule, but I will read up on the links you sent to learn more.

**Comment by bobbymcr** [comment]
Sure. FWIW I see the same recommendation on MSDN with no exception or
qualification about PCH:
https://msdn.microsoft.com/en-us/library/5cb46ksf.aspx

"In general, avoid putting using directives in header files (*.h) because
any file that includes that header will bring everything in the namespace
into scope, which can cause name hiding and name collision problems that
are very difficult to debug. Always use fully qualified names in a header
file. If those names get too long, you can use a namespace alias to shorten
them. (See below.)"

**Comment by JayBazuzi** [comment]
A related concern is that you can't just grab okra.h and #include it in your project and write tests. You have to have a bunch of other STL headers first. This is the "headers should be self-contained" rule.

**Comment by JayBazuzi** [comment]
Fixed in #43f81a0

**Comment by JayBazuzi** [comment]
I marked this as closed because it has been fixed, but there's no test for it. I don't like when there's something important that doesn't have a test.

One option for testing would be a step in a CI process that verifies that there are no namespace `using`s in .h files. Something to consider after we have CI.
